spring:
  profiles:
    active:
    - mongo-db
  application:
    name: customer-service
server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true